name: Update fetch link in README with Latest Commit ID

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest commit ID
        id: commit-id
        run: echo "::set-output name=commit_id; value=$(git rev-parse HEAD)"

      - name: Update README.md
        run: sed -i -r "s/archive\/\w{40}/archive\/${{ steps.commit-id.outputs.commit_id }}/g" README.md


      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md with commit ID (${{ steps.commit-id.outputs.SHA1SHORT }})"
          git push origin main
