name: Update fetch link in README with Latest Commit ID

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest commit ID
      id: commit
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Update README.md
      run: |
        sed -i "s/module-sys\/archive\/.+\.tar\.gz/module-sys\/archive\/${{ steps.update-readme.outputs.commit_id }}.tar.gz/g" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add README.md
        git commit -m "Update README.md with latest commit ID"
        git push